/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import modelos_concretos.CamisetaStandart;
import modelos_concretos.CamisetaEstampada;
import modelos_concretos.CamisetaPersonalizada;
import modelos_concretos.CamisetaTematica;

/**
 *
 * @author roger
 */
public class ViewCamisetaDecorator extends javax.swing.JFrame {

    CamisetaStandart standart;
    CamisetaEstampada estampada;
    CamisetaPersonalizada personalizada;
    CamisetaTematica tematica;

    /**
     * Creates new form ViewCamisetaDecorator
     */
    public ViewCamisetaDecorator() {

        standart = new CamisetaStandart();
        initComponents();
        jCheckBoxStandart.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDecoratorCamiseta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBoxStandart = new javax.swing.JCheckBox();
        jCheckBoxEstampada = new javax.swing.JCheckBox();
        jCheckBoxPersonalizada = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaidaCamiseta = new javax.swing.JTextArea();
        jTextFieldValorStandart = new javax.swing.JTextField();
        jTextFieldValorEstampada = new javax.swing.JTextField();
        jTextFieldValorPersonalizada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonIncluirNoCarrinho = new javax.swing.JButton();
        jCheckBoxTematica = new javax.swing.JCheckBox();
        jTextFieldValorTematica = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Padrão de Projeto Decorator");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Camisetas Roger");

        jCheckBoxStandart.setText("Standart");
        jCheckBoxStandart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStandartActionPerformed(evt);
            }
        });

        jCheckBoxEstampada.setText("Estampada");
        jCheckBoxEstampada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEstampadaActionPerformed(evt);
            }
        });

        jCheckBoxPersonalizada.setText("Pesonalizada");
        jCheckBoxPersonalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPersonalizadaActionPerformed(evt);
            }
        });

        jTextAreaSaidaCamiseta.setColumns(20);
        jTextAreaSaidaCamiseta.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaidaCamiseta);

        jTextFieldValorStandart.setText("30.0");

        jTextFieldValorEstampada.setEditable(false);

        jTextFieldValorPersonalizada.setEditable(false);

        jLabel2.setText("Escolha seu perfil");

        jButtonIncluirNoCarrinho.setText("Incluir no Carrinho");
        jButtonIncluirNoCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirNoCarrinhoActionPerformed(evt);
            }
        });

        jCheckBoxTematica.setText("Temática");
        jCheckBoxTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxTematicaActionPerformed(evt);
            }
        });

        jTextFieldValorTematica.setEditable(false);

        javax.swing.GroupLayout jPanelDecoratorCamisetaLayout = new javax.swing.GroupLayout(jPanelDecoratorCamiseta);
        jPanelDecoratorCamiseta.setLayout(jPanelDecoratorCamisetaLayout);
        jPanelDecoratorCamisetaLayout.setHorizontalGroup(
            jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDecoratorCamisetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDecoratorCamisetaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(232, 232, 232))
                    .addGroup(jPanelDecoratorCamisetaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(jPanelDecoratorCamisetaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addGroup(jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDecoratorCamisetaLayout.createSequentialGroup()
                        .addComponent(jCheckBoxStandart)
                        .addGap(47, 47, 47)
                        .addComponent(jTextFieldValorStandart)
                        .addGap(196, 196, 196))
                    .addGroup(jPanelDecoratorCamisetaLayout.createSequentialGroup()
                        .addGroup(jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxEstampada)
                            .addComponent(jCheckBoxPersonalizada)
                            .addComponent(jCheckBoxTematica))
                        .addGap(20, 20, 20)
                        .addGroup(jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDecoratorCamisetaLayout.createSequentialGroup()
                                .addComponent(jTextFieldValorTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 56, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDecoratorCamisetaLayout.createSequentialGroup()
                                .addGroup(jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldValorEstampada, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldValorPersonalizada))
                                .addGap(56, 56, 56)))
                        .addComponent(jButtonIncluirNoCarrinho)
                        .addContainerGap())))
        );
        jPanelDecoratorCamisetaLayout.setVerticalGroup(
            jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDecoratorCamisetaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxStandart)
                    .addComponent(jTextFieldValorStandart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxEstampada)
                    .addComponent(jTextFieldValorEstampada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIncluirNoCarrinho)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxPersonalizada)
                    .addComponent(jTextFieldValorPersonalizada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDecoratorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxTematica)
                    .addComponent(jTextFieldValorTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDecoratorCamiseta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDecoratorCamiseta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxStandartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStandartActionPerformed
        if (jCheckBoxStandart.isSelected()) {
            jTextFieldValorStandart.requestFocus();
        } else {
            jTextFieldValorStandart.setText("");
        }
    }//GEN-LAST:event_jCheckBoxStandartActionPerformed

    private void jCheckBoxEstampadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEstampadaActionPerformed
        estampada = new CamisetaEstampada(standart);
        if (jCheckBoxEstampada.isSelected()) {
            jTextFieldValorEstampada.setText(estampada.getPrecoEstampa() + "");
        } else {
            jTextFieldValorEstampada.setText("");
        }
    }//GEN-LAST:event_jCheckBoxEstampadaActionPerformed

    private void jCheckBoxPersonalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPersonalizadaActionPerformed
        personalizada = new CamisetaPersonalizada(standart);
        if (jCheckBoxPersonalizada.isSelected()) {
            jTextFieldValorPersonalizada.setText(personalizada.getPrecoPersonalizado() + "");
        } else {
            jTextFieldValorEstampada.setText("");
        }
    }//GEN-LAST:event_jCheckBoxPersonalizadaActionPerformed

    private void jButtonIncluirNoCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirNoCarrinhoActionPerformed
        try {
            boolean camisetaStandart = jCheckBoxStandart.isSelected();
            boolean camisetaEstampada = jCheckBoxEstampada.isSelected();
            boolean camisetaPersonalizada = jCheckBoxPersonalizada.isSelected();
            boolean camisetaTematica = jCheckBoxTematica.isSelected();

            standart.setTipo("Standart");
            standart.setPreco(Double.parseDouble(jTextFieldValorStandart.getText()));

            if (camisetaStandart) {
                jTextFieldValorStandart.requestFocus();
                jTextAreaSaidaCamiseta.setText(standart + "");
            }
            if (camisetaEstampada) {
                estampada = new CamisetaEstampada(standart);
                jTextAreaSaidaCamiseta.setText(estampada + "");
            }
            if (camisetaPersonalizada) {
                personalizada = new CamisetaPersonalizada(standart);
                jTextAreaSaidaCamiseta.setText(personalizada + "");
            }
            if (camisetaTematica) {
                tematica = new CamisetaTematica(standart);
                jTextAreaSaidaCamiseta.setText(tematica + "");
            }
            if (camisetaStandart && camisetaEstampada && camisetaPersonalizada) {
                personalizada = new CamisetaPersonalizada(new CamisetaEstampada(standart));
                jTextAreaSaidaCamiseta.setText(personalizada + "");
            }
            //Ver essa parte do código com prof. Eugênio, não está entrando nesta condição
            if (camisetaStandart && camisetaEstampada && camisetaPersonalizada && camisetaTematica) {
                tematica = new CamisetaTematica(new CamisetaPersonalizada(new CamisetaEstampada(standart)));
                jTextAreaSaidaCamiseta.setText(tematica + "");
            }
            if (camisetaEstampada && camisetaTematica) {
                tematica = new CamisetaTematica(new CamisetaEstampada(standart));
                jTextAreaSaidaCamiseta.setText(tematica + "");
            }
            if (camisetaPersonalizada && camisetaTematica) {
                tematica = new CamisetaTematica(new CamisetaPersonalizada(standart));
                jTextAreaSaidaCamiseta.setText(tematica + "");
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao incluir esta compra no carrinho");
        }
    }//GEN-LAST:event_jButtonIncluirNoCarrinhoActionPerformed

    private void jCheckBoxTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxTematicaActionPerformed
        tematica = new CamisetaTematica(standart);
        if (jCheckBoxTematica.isSelected()) {
            jTextFieldValorTematica.setText(tematica.getPrecoTematico() + "");
        } else {
            jTextFieldValorTematica.setText("");
        }
    }//GEN-LAST:event_jCheckBoxTematicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCamisetaDecorator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCamisetaDecorator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCamisetaDecorator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCamisetaDecorator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCamisetaDecorator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIncluirNoCarrinho;
    private javax.swing.JCheckBox jCheckBoxEstampada;
    private javax.swing.JCheckBox jCheckBoxPersonalizada;
    private javax.swing.JCheckBox jCheckBoxStandart;
    private javax.swing.JCheckBox jCheckBoxTematica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelDecoratorCamiseta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSaidaCamiseta;
    private javax.swing.JTextField jTextFieldValorEstampada;
    private javax.swing.JTextField jTextFieldValorPersonalizada;
    private javax.swing.JTextField jTextFieldValorStandart;
    private javax.swing.JTextField jTextFieldValorTematica;
    // End of variables declaration//GEN-END:variables
}
